name: education
description: An educational and E-learning application powered by Syntec Flow Company
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"
#  flutter: 3.0.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  http: ^0.13.5
  dartz: ^0.10.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.3
  intro_slider: ^3.0.9
  animate_do: ^2.1.0
  lottie: ^1.4.1
  form_builder_validators: ^8.3.0
  progress_state_button: ^1.0.4
  cached_network_image: ^3.2.1
  infinite_scroll_pagination: ^3.2.0
  shimmer: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^5.1.0
  animations: ^2.0.3
  expandable: ^5.0.1
  font_awesome_flutter: ^10.1.0
  jwt_decoder: ^2.0.1
  better_player: ^0.0.83
  flutter_widget_from_html: ^0.8.5
  palette_generator: ^0.3.3+1
  equatable: ^2.0.3
  auto_route: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  hive_generator: ^1.1.3
  auto_route_generator: ^4.2.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/locales/
    - assets/svg/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
